// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OceanaAura.Persistence.AppDbContext;

#nullable disable

namespace OceanaAura.Persistence.Migrations
{
    [DbContext(typeof(OeanaAuraDbContext))]
    [Migration("20241213114108_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OceanaAura.Domain.Entities.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("OceanaAura.Domain.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("OceanaAura.Domain.Entities.LookUp.LookUpCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("lookUpCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9005),
                            Description = "Region Country",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "المنطقة",
                            NameEn = "Region"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9017),
                            Description = "Payment",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "طرق الدفع",
                            NameEn = "Payment"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9019),
                            Description = "PriceCountry",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "عملة البلد",
                            NameEn = "Price Country"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9021),
                            Description = "Language",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "لغة",
                            NameEn = "Language"
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9022),
                            Description = "Product Color",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "لون المنتج",
                            NameEn = "Product Color"
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9024),
                            Description = "Product Size",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "حجم المنتج",
                            NameEn = "Product Size"
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9025),
                            Description = "Product Additional",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "اضافات للمنتج",
                            NameEn = "Product Additional"
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9027),
                            Description = "Order Status",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "حالات الطلب",
                            NameEn = "Order Status"
                        },
                        new
                        {
                            CategoryId = 9,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9028),
                            Description = "Product Category",
                            Id = 0,
                            IsDeleted = false,
                            NameAr = "نوع المنتج",
                            NameEn = "Product Category"
                        });
                });

            modelBuilder.Entity("OceanaAura.Domain.Entities.LookUp.LookUpEntity", b =>
                {
                    b.Property<int>("LookUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LookUpId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LookupCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LookUpId");

                    b.HasIndex("LookupCategoryId");

                    b.ToTable("lookups");

                    b.HasData(
                        new
                        {
                            LookUpId = 100,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9131),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 1,
                            NameAr = "الأردن",
                            NameEn = "Jordan"
                        },
                        new
                        {
                            LookUpId = 101,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9133),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 1,
                            NameAr = "الإمارات العربية المتحدة",
                            NameEn = "United Arab Emirates"
                        },
                        new
                        {
                            LookUpId = 200,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9134),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 2,
                            NameAr = "دفع كاش",
                            NameEn = "Cash On Delivery"
                        },
                        new
                        {
                            LookUpId = 400,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9136),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 4,
                            NameAr = "الأردن",
                            NameEn = "JOR"
                        },
                        new
                        {
                            LookUpId = 401,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9138),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 4,
                            NameAr = "الإمارات العربية المتحدة",
                            NameEn = "UAE"
                        },
                        new
                        {
                            LookUpId = 402,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9139),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 4,
                            NameAr = "دولار",
                            NameEn = "USD"
                        },
                        new
                        {
                            LookUpId = 300,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9140),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 3,
                            NameAr = "الأنجليزي",
                            NameEn = "En"
                        },
                        new
                        {
                            LookUpId = 301,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9142),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 3,
                            NameAr = "العربية",
                            NameEn = "Ar"
                        },
                        new
                        {
                            LookUpId = 500,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9143),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أسود",
                            NameEn = "Black"
                        },
                        new
                        {
                            LookUpId = 501,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9144),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "وردي فاتح",
                            NameEn = "Light Pink"
                        },
                        new
                        {
                            LookUpId = 502,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9146),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أزرق كحلي",
                            NameEn = "Navy Blue"
                        },
                        new
                        {
                            LookUpId = 503,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9148),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أخضر عسكري",
                            NameEn = "Army Green"
                        },
                        new
                        {
                            LookUpId = 504,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9149),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أزرق فاتح",
                            NameEn = "Baby Blue"
                        },
                        new
                        {
                            LookUpId = 505,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9151),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أزرق",
                            NameEn = "Blue"
                        },
                        new
                        {
                            LookUpId = 506,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9152),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أخضر",
                            NameEn = "Green"
                        },
                        new
                        {
                            LookUpId = 507,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9153),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "بنفسجي",
                            NameEn = "Purple"
                        },
                        new
                        {
                            LookUpId = 508,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9155),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أزرق سماوي",
                            NameEn = "Aqua Blue"
                        },
                        new
                        {
                            LookUpId = 509,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9156),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "وردي",
                            NameEn = "Pink"
                        },
                        new
                        {
                            LookUpId = 510,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9157),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "برتقالي",
                            NameEn = "Orange"
                        },
                        new
                        {
                            LookUpId = 511,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9159),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أصفر",
                            NameEn = "Yellow"
                        },
                        new
                        {
                            LookUpId = 512,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9160),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أحمر",
                            NameEn = "Red"
                        },
                        new
                        {
                            LookUpId = 513,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9162),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "لون متدرج",
                            NameEn = "Gradient Color"
                        },
                        new
                        {
                            LookUpId = 514,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9163),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "بامبي",
                            NameEn = "Bambi"
                        },
                        new
                        {
                            LookUpId = 515,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9164),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "لون البشرة",
                            NameEn = "Nude"
                        },
                        new
                        {
                            LookUpId = 516,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9166),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 5,
                            NameAr = "أزرق كوبالت",
                            NameEn = "Cobalt Blue"
                        },
                        new
                        {
                            LookUpId = 600,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9168),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 6,
                            NameAr = "355 مل",
                            NameEn = "355ml"
                        },
                        new
                        {
                            LookUpId = 601,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9169),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 6,
                            NameAr = "650 مل",
                            NameEn = "650ml"
                        },
                        new
                        {
                            LookUpId = 602,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9171),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 6,
                            NameAr = "740 مل",
                            NameEn = "740ml"
                        },
                        new
                        {
                            LookUpId = 603,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9172),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 6,
                            NameAr = "1 لتر",
                            NameEn = "1 Liter"
                        },
                        new
                        {
                            LookUpId = 604,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9173),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 6,
                            NameAr = "1.2 لتر",
                            NameEn = "1.2 Liter"
                        },
                        new
                        {
                            LookUpId = 700,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9175),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 7,
                            NameAr = "غطاء مغناطيسي",
                            NameEn = "Magnetic Lid"
                        },
                        new
                        {
                            LookUpId = 701,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9176),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 7,
                            NameAr = "تخصيص",
                            NameEn = "Customization"
                        },
                        new
                        {
                            LookUpId = 702,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9177),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 7,
                            NameAr = "رسوم التوصيل",
                            NameEn = "Delivery Fee"
                        },
                        new
                        {
                            LookUpId = 800,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9179),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 8,
                            NameAr = "معلق",
                            NameEn = "Pending"
                        },
                        new
                        {
                            LookUpId = 801,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9261),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 8,
                            NameAr = "تم التأكيد",
                            NameEn = "Confirmed"
                        },
                        new
                        {
                            LookUpId = 802,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9262),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 8,
                            NameAr = "تم الشحن",
                            NameEn = "Shipped"
                        },
                        new
                        {
                            LookUpId = 803,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9264),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 8,
                            NameAr = "قيد التوصيل",
                            NameEn = "Out for Delivery"
                        },
                        new
                        {
                            LookUpId = 804,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9265),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 8,
                            NameAr = "تم التوصيل",
                            NameEn = "Delivered"
                        },
                        new
                        {
                            LookUpId = 805,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9267),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 8,
                            NameAr = "مكتمل",
                            NameEn = "Completed"
                        },
                        new
                        {
                            LookUpId = 806,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9268),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 8,
                            NameAr = "ملغى",
                            NameEn = "Cancelled"
                        },
                        new
                        {
                            LookUpId = 900,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9269),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 9,
                            NameAr = "مطرة ماء",
                            NameEn = "Bottle"
                        },
                        new
                        {
                            LookUpId = 901,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9271),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 9,
                            NameAr = "غطاء",
                            NameEn = "lid"
                        },
                        new
                        {
                            LookUpId = 902,
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 12, 13, 14, 41, 8, 703, DateTimeKind.Local).AddTicks(9272),
                            Id = 0,
                            IsDeleted = false,
                            LookupCategoryId = 9,
                            NameAr = "المحاية",
                            NameEn = "Rubber"
                        });
                });

            modelBuilder.Entity("OceanaAura.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceJOR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceUAE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OceanaAura.Domain.Entities.Image", b =>
                {
                    b.HasOne("OceanaAura.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OceanaAura.Domain.Entities.LookUp.LookUpEntity", b =>
                {
                    b.HasOne("OceanaAura.Domain.Entities.LookUp.LookUpCategory", "LookupCategory")
                        .WithMany("lookUps")
                        .HasForeignKey("LookupCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupCategory");
                });

            modelBuilder.Entity("OceanaAura.Domain.Entities.LookUp.LookUpCategory", b =>
                {
                    b.Navigation("lookUps");
                });

            modelBuilder.Entity("OceanaAura.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
